In [13]:
import pandas as pd
import csv

**question 1**

In [3]:
pd.__version__

'2.1.0'

In [26]:
df = pd.read_csv("C:/Users/axelb/Desktop/ml-zoomcamp/dataset_hmw1.csv")

In [30]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

**question 2**

In [33]:
df.shape[1]

10

**question 3**

In [34]:
df.isnull().count()

longitude             20640
latitude              20640
housing_median_age    20640
total_rooms           20640
total_bedrooms        20640
population            20640
households            20640
median_income         20640
median_house_value    20640
ocean_proximity       20640
dtype: int64

**question 4**

In [39]:
df.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [40]:
df.groupby('ocean_proximity').nunique().count()

longitude             5
latitude              5
housing_median_age    5
total_rooms           5
total_bedrooms        5
population            5
households            5
median_income         5
median_house_value    5
dtype: int64

**question 5**

In [58]:
(df[df['ocean_proximity'] == "NEAR BAY"]).median_house_value.mean()

259212.31179039303

In [59]:
dt_bn = df[df['ocean_proximity'] == "NEAR BAY"]
dt_bn

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
19067    -122.45     38.28                20.0       3306.0           503.0   
19068    -122.47     38.29                14.0       3732.0           846.0   
19069    -122.45     38.27                25.0       5024.0           881.0   
19077    -122.49     38.27                 8.0       5092.0           988.0   
19104    -122.51     38.17                 8.0       5875.0          1115.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
19067      1374.0       460.0         5.7984            297600.0   
19068      1277.0       775.0         2.5658            208000.0   
19069      1994.0       838.0         4.2237            262300.0   
19077      1657.0       936.0         3.5625            213200.0   
19104      2808.0      1029.0         3.6392            246300.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
19067        NEAR BAY  
19068        NEAR BAY  
19069        NEAR BAY  
19077        NEAR BAY  
19104        NEAR BAY  

[2290 rows x 10 columns]

In [60]:
dt_bn.median_house_value.mean()

259212.31179039303

**question 6**

In [62]:
avg_total_bedrooms = df.total_bedrooms.mean()
avg_total_bedrooms

537.8705525375618

In [78]:
df[
    df.total_bedrooms.isnull()
]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
290      -122.16     37.77                47.0       1256.0             NaN   
341      -122.17     37.75                38.0        992.0             NaN   
538      -122.28     37.78                29.0       5154.0             NaN   
563      -122.24     37.75                45.0        891.0             NaN   
696      -122.10     37.69                41.0        746.0             NaN   
...          ...       ...                 ...          ...             ...   
20267    -119.19     34.20                18.0       3620.0             NaN   
20268    -119.18     34.19                19.0       2393.0             NaN   
20372    -118.88     34.17                15.0       4260.0             NaN   
20460    -118.75     34.29                17.0       5512.0             NaN   
20484    -118.72     34.28                17.0       3051.0             NaN   

       population  households  median_income  median_house_value  \
290         570.0       218.0         4.3750            161900.0   
341         732.0       259.0         1.6196             85100.0   
538        3741.0      1273.0         2.5762            173400.0   
563         384.0       146.0         4.9489            247100.0   
696         387.0       161.0         3.9063            178400.0   
...           ...         ...            ...                 ...   
20267      3171.0       779.0         3.3409            220500.0   
20268      1938.0       762.0         1.6953            167400.0   
20372      1701.0       669.0         5.1033            410700.0   
20460      2734.0       814.0         6.6073            258100.0   
20484      1705.0       495.0         5.7376            218600.0   

      ocean_proximity  
290          NEAR BAY  
341          NEAR BAY  
538          NEAR BAY  
563          NEAR BAY  
696          NEAR BAY  
...               ...  
20267      NEAR OCEAN  
20268      NEAR OCEAN  
20372       <1H OCEAN  
20460       <1H OCEAN  
20484       <1H OCEAN  

[207 rows x 10 columns]

In [96]:
df[
    df.total_bedrooms.isnull()
] = df[df.total_bedrooms.isnull()].fillna(avg_total_bedrooms)

In [100]:
df.total_bedrooms.isnull()

0        False
1        False
2        False
3        False
4        False
         ...  
20635    False
20636    False
20637    False
20638    False
20639    False
Name: total_bedrooms, Length: 20640, dtype: bool

In [101]:
df[
    df.total_bedrooms.isnull()
]

Empty DataFrame
Columns: [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, median_house_value, ocean_proximity]
Index: []

In [113]:
avg_total_bedrooms_new = df.total_bedrooms.mean()
avg_total_bedrooms_new.round(3)

537.871

In [114]:
avg_total_bedrooms.round(3)

537.871

In [129]:
avg_total_bedrooms.round(3) == avg_total_bedrooms_new.round(3)

True

**question 7**

In [148]:
df_island = df[df['ocean_proximity']=="ISLAND"]
df_island

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [149]:
df_island_new = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
df_island_new 

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [150]:
X = df_island_new.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [151]:
X.T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [152]:
XTX = X.dot(X.T)
XTX

array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [157]:
XTX.shape

(5, 5)

In [153]:
import numpy as np

In [154]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 4.50889141e+08, -2.65092831e+09,  2.66146909e+09,
        -5.26157398e+08,  5.04760603e+08],
       [ 2.60444475e+11, -8.57212683e+10, -2.18771394e+10,
         5.28097320e+11, -9.96480838e+11],
       [-2.81125831e+11,  9.36268739e+10,  2.24292933e+10,
        -5.69400064e+11,  1.07463035e+12],
       [ 1.50907516e+11, -5.52172767e+10, -6.69134384e+09,
         3.02798151e+11, -5.72439948e+11],
       [-2.33928769e+11,  8.73028262e+10,  8.53028316e+09,
        -4.68398445e+11,  8.85843939e+11]])

In [156]:
XTX_inv.shape

(5, 5)

In [137]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [140]:
XTX_inv.shape

(5, 5)

In [141]:
(X.T).shape

(3, 5)

In [167]:
prod = (X.T).dot(XTX_inv)
prod

array([[-0.00292969, -0.0151825 ,  0.00458622,  0.03063965, -0.0020752 ],
       [-0.07421875, -0.00274658,  0.00222397, -0.09912109, -0.06201172],
       [ 0.00195312,  0.00033569, -0.00824165,  0.01489258, -0.00561523]])

In [143]:
prod.shape

(3, 5)

In [168]:
w = prod.dot(y)
w

array([   9.09042358, -252.03552246,    3.2913208 ])

In [169]:
w[-1]

3.29132080078125